### ISSUE TITLE
Support RepairItem does not work.

### ISSUE THREAD

**Issue by ha1331** [TimVN/opskins-api#1]
The error is opskins expects a post request, this api does get.

I'm pretty sure you would need to pass the method post as a parameter (defaults to get) to request at modules/support.js 

```
RepairItem: (saleId) => {
    return opRequest.make('ISupport/RepairItem/v1', { saleid: saleId });
}
```

I think that should do: 
`return opRequest.make('ISupport/RepairItem/v1', { saleid: saleId }, "post");`

**Comment by laterbreh** [comment]
Resolved with pull request.
#3
